# Generated by Django 4.1 on 2022-09-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_likedposts_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likedposts',
            name='post',
            field=models.ManyToManyField(to='network.post'),
        ),
    ]
