# Generated by Django 4.1 on 2023-05-04 15:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0048_remove_following_following_remove_following_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 18, 11, 38, 616865)),
        ),
    ]
